name: Botonic plugin ai agents tests

on:
  push:
    paths:
      - 'packages/botonic-plugin-ai-agents/**'
      - '.github/workflows/botonic-plugin-ai-agents-tests.yml'
  workflow_dispatch:

jobs:
  botonic-plugin-ai-agents-tests:
    uses: ./.github/workflows/botonic-common-workflow.yml
    secrets: inherit #pragma: allowlist secret
    with:
      PACKAGE_NAME: Botonic plugin ai agents tests
      PACKAGE: botonic-plugin-ai-agents
      BUILD_COMMAND: 'cd ../botonic-core && npm run build && cd ../botonic-plugin-ai-agents && npm run build'
      LINT_COMMAND: npm run lint:check
      NEEDS_CODECOV_UPLOAD: 'yes'
